name: mdmtaskweb
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - ipywidgets=8.1.1
  - matplotlib-base=3.5.1
  - mdtraj
  - nglview=3.0.8
  - networkx=2.6.1
  - pandas
  - pandoc
  - python=3.8
  - scikit-learn
  - seaborn
  - conda-forge::jupyterlab
